name: hyp3-water-mask
channels:
  - conda-forge
dependencies:
  - python~=3.7
  - pip
  # For packaging, and testing
  - setuptools
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - gdal
  - imageio
  - importlib_metadata
  - tensorflow>=1.15
  - keras
  - lxml
  - matplotlib
  - netCDF4
  - numpy
  - pillow
  - proj
  - psycopg2
  - pyshp
  - requests
  - scipy
  - six
  - statsmodels
  - pip:
    # for packaging and testing
    - s3pypi
    - setuptools-scm[toml]
    - safety
    # For running
    - --trusted-host hyp3-pypi.s3-website-us-east-1.amazonaws.com
      --extra-index-url http://hyp3-pypi.s3-website-us-east-1.amazonaws.com
    - hyp3lib
    - hyp3proclib